version: "3"
services:
  api:
    image: lineofflight/frankfurter
    container_name: frankfurter-api
    restart: no
    pull_policy: always
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 2s
      timeout: 20s
      retries: 10
