name: Audit dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
      branches: ["main"]
      paths:
          - '.github/workflows/**'
          - '**/Cargo.*'
  pull_request:
      branches: ["main"]
      paths:
          - '.github/workflows/**'
          - '**/Cargo.*'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
            arguments: --workspace
